### ISSUE TITLE
Create page with date as input and generate report button

### ISSUE THREAD

**Issue by nitika-goel** [plotx/smart-contracts#78]
Create a web page for generating "challenge " script result by entering date

**Comment by Samagra-Dev** [comment]
Description: If we generate a report from 12 PM UTC 23rd Oct to 12 PM UTC 24th Oct, then, only the hourly predictions will be there in the report since hourly markets are the only ones which get settled within the 24 hours time frame. Since we have said that predictions made in any daily market that is created in the duration of the challenge (Post 12 PM UTC 23rd Oct) will be considered for that day's leaderboard on which the daily market is settled, we need to take care of this while calculating the results.

Example: Predictions made in the daily market that is created at 2 PM UTC 23rd Oct (Day 1 of the challenge) will be settled at 2 PM UTC 25th Oct. Hence, predictions in this market will be considered for the leaderboard that has the report from 12 PM UTC 25th Oct to 12 PM UTC 26th Oct, that is the Day 3 leaderboard.

@nitika-goel @ankitnirwal

**Comment by bhavya-plotx** [comment]
This was done. Thanks @ankitnirwal
