### ISSUE TITLE
Negative amount shown in Pending Rewards

### ISSUE THREAD

**Issue by bhavya-plotx** [plotx/smart-contracts#98]
**Describe the bug**
Negative amount being shown in pending rewards

**To Reproduce**
1. Go to https://beta.plotx.io/userAccount/ETH-USD/Hourly/0x36fA230ec53c7A18a481A9CbD31B84E976a1d7cc'
2. See error wrt negative PLOTs to claim

**Expected behavior**
After claiming my rewards, the pending rewards should be 0 or a positive number. 

**Screenshots**
![image](https://user-images.githubusercontent.com/73012963/97773102-14daba80-1b73-11eb-9f13-cbd284f97341.png)

**Desktop (please complete the following information):**
 - Browser: Opera
 - Extension: MetaMask

**Additional context**
Making sure the pending rewards are either positive or zero

**Comment by ankit5902** [comment]
**Describe the bug**
Negative amount being shown in pending rewards

ETH Address : 


**To Reproduce**
Steps to reproduce the behavior:
1. Go to My Account tab
2. See error wrt negative PLOTs to claim.


**Expected behavior**
After claiming my rewards, the pending rewards should be 0 or a positive number.


**Screenshots**

![image](https://user-images.githubusercontent.com/36991769/97777188-90009880-1b94-11eb-90bf-0dfbba9d9c10.png)

**Comment by venkateshsys** [comment]
@Samagra-Dev @bhavya-plotx 
Resolved the DB sync issue. Please confirm with the user and close it.

![image](https://user-images.githubusercontent.com/48546261/97810415-afcdb480-1c99-11eb-8f5e-5286610a3322.png)

![image](https://user-images.githubusercontent.com/48546261/97810432-c6740b80-1c99-11eb-93cf-28c9d9ecab9f.png)

**Comment by bhavya-plotx** [comment]
Looks correct to me. Closing this issue.
